resolver: lts-18.10


packages:
  - ./aatejcpmjq-tdepajmtvx-fhrxckzqsk
  - ./aeisxcbrdg-lcjurvvojz-lezuipxdai
  - ./afterjznqu-mkszchedmv-cemvtpwxvm
  - ./aiboxtftww-twgwqzwbgz-dczjcqumyf
  - ./aicczlxqqo-zpjknbeumz-abqtjkcjjx
  - ./akgvmhdcfs-edgsqlgfhp-ducbdjoqto
  - ./allegsetfg-gnzbpmselo-wsxeozcgkc
  - ./ambqfekzlo-giypknqooz-ybdhisbtgi
  - ./amtcdurjli-uwlpznlrpv-utcmngyspj
  - ./annwckljmq-muyfsitolt-edoxonacun
  - ./anurrwvbsu-gdfwwlpqgg-sxleewodnh
  - ./apgymziwpt-hfuoxfazde-mduxjobqdb
  - ./aqnjlfuwxk-ymqzgquqlr-vmgxdtndwx
  - ./atgnezedgv-lbskucbixg-bdkbwtkusi
  - ./avffwahegf-oqtbqrvtos-mvxypgiome
  - ./avvnstljbf-eqvbiqanvb-epetargzft
  - ./axwjpkrvbz-tjiqqivkjb-vdcyriwmgb
  - ./ayqaodtiqr-lyoodcipiw-hvmfzfurzz
  - ./aziqfcqzmy-iqnacgdwjr-mcroybnavg
  - ./bartgulhih-fvuwxcitsk-foqrmqxrka
  - ./bibynmwkdi-aowoigbqpz-mmzeeodbzp
  - ./bitzgjembd-vaymfjlvqk-iuthenagvi
  - ./blldacdoaq-nwjshzvehs-pernmdonjn
  - ./bmnsexcmla-uhiigkzpho-fecljrnpui
  - ./bnshqvvvle-ouaafahzqf-qoefqifeej
  - ./boardlbhyl-fwkrjpkdjj-uanqxbjouz
  - ./bptlgjyyrq-zfresiwsaf-noihykajkm
  - ./bqgqgjwckd-ehngmouflf-rxjnhvlppm
  - ./bulvlkdfna-dejoouyizu-hyaxeldtbf
  - ./cabtqowckd-tkohzqixsj-umbwepqaep
  - ./chrhenkcyg-gsljwlmdky-tjpdjulxyw
  - ./cimzacikqn-syzmmnqrci-udyctttsxo
  - ./civunfdiag-tziozhaunn-zdkpvlcwwa
  - ./cohucyawlw-ayzclskait-eovrurpbdf
  - ./cqgeqmqnyg-hbyqhbbbdm-eazabhchvh
  - ./crgtvuiocv-axtjsngogp-nermqbnorb
  - ./ctinvzdtjm-hfchrxvxxm-gpgeiyxotj
  - ./cvlrjouiri-wbgjtuteng-igggcgpiff
  - ./cykbpqjxqd-sblzneieby-ufuuzcgxxy
  - ./dfutqzyvlx-lzxlmmeykz-mgbqnmngwl
  - ./djeajpnann-bjxulznqzx-dcwzzgdcyo
  - ./dkqmdspphm-upsilnxisj-zafbrsprsq
  - ./dojgfsfyyc-ethrjmfwim-hxikgfjvrh
  - ./dubevazgvk-nclmplqrpa-vdmucofxpc
  - ./dxjifexidt-ceqgnulqjm-hyhfgxebyz
  - ./dxzlydcoqy-hozbpoykds-zpmnquaytb
  - ./dyzkvuhlvz-hifjbbfevp-qcdwcazncr
  - ./eaanawwfrj-acdutlfxan-mvvlnkyckf
  - ./ebyfzvaadd-akxeqhfdsa-kjiwbyvtth
  - ./efifqufbzb-rmxukseuia-qtknhufiaz
  - ./efydwdvkud-btanytcyal-whiuekkrfo
  - ./ehjuaeqivl-nzhhevcriz-kbvxylsitr
  - ./ehlidblogq-fjtiopyjqr-zeividntgy
  - ./ehvegiloaf-gcpdatbhdo-lzwtyrqhoh
  - ./esjvmxceqv-jrjkdrvbgn-qfyvudaund
  - ./etlyrgxsia-bttjzmnkkc-ggszlfphiz
  - ./etnxirubqy-dvsnrbmtbe-wwlkbvjnsk
  - ./eydojexqnq-mxbcyokmee-rgsklmgkgh
  - ./fcxxqvszev-nfnbdbofvi-zrgzlqndnk
  - ./fdxitgbslx-kusfamsfng-ctqbkqzlzf
  - ./filfoyrzts-ivuunoesjn-jdndugpdku
  - ./fjiwadmxge-aqjkxoqtiw-xcrotcqoci
  - ./flhpkvdlib-mhpddozgax-oijajyqblg
  - ./fpydkaffkt-vgotjnxvoi-cthwyleiuo
  - ./fseomupgyr-jsejlaqibm-frumuzhsqt
  - ./fyctbvpzvv-jlmybfgnil-macvvuctpr
  - ./gcencghsrd-meylbcllzm-pxzhgfnhah
  - ./gdwlagyykg-ghabguoqww-ggmkvuvfls
  - ./gkaepqbpvz-rmnnsxyjso-hoqbpktsuw
  - ./gkjuhkyyqj-jozfvwcjya-gxibjpvgiy
  - ./glihvutyjc-vljgwvnbeu-acqhevrzxx
  - ./gqjhiyyqcx-rgghdzvqcm-urchzygimk
  - ./gqneousnmf-mnqkugguei-kcgvtbvdhv
  - ./grbmmefqea-lcmjjyihps-xgchqjhaqf
  - ./groebrasbp-dyjnbimgiu-skwbmqsqgr
  - ./gsddpmgnqm-lrasmiwcib-akeauejxgu
  - ./gselmrlvgc-jtynxiqcar-ahgrxgmatz
  - ./gtcvzcyrqh-fomvyfnmxq-bonfggbrvq
  - ./gwfrzlktem-ugascxpvck-kuyeafauno
  - ./gymqqiksln-ycqlesvmbu-mrzmpdrmlm
  - ./gyqpganuhr-yhqbkhlsgg-yoptkmgzid
  - ./harreirudm-lfjzkeohgz-hxnorvwohu
  - ./hnjxwkplhx-fqwdrtgbfb-uusnyvrehs
  - ./hrdpcemlbl-vflmuqdmrm-qzgpglglqp
  - ./hubczbdguw-dzlbwltvxf-mxdwavejyx
  - ./hwocehislh-ahiexjrold-azgbpkteor
  - ./hyvhvjnisq-lvthavwoui-ptfwyvqrwk
  - ./ibcsaqswoj-kghjffqrcb-fifltunohv
  - ./ichjcyhicw-wzhlponhfw-znkokswool
  - ./icjwsujuik-dxgvtezivw-xkzrtwpdfq
  - ./idfsobyivo-lllmlqubao-kxtjqgsjuk
  - ./idgzpedoaf-dbfjwldocy-karcmrrnvw
  - ./ifdcennmlo-islfnqxiqy-enzxaagooh
  - ./ihijfecmzj-ljxkhsaltz-tgoyvsagej
  - ./ilkyzffjvt-vofxojcjsi-peeigbgsse
  - ./irnnsxssyn-smvaxwghzf-nispjafufa
  - ./ishxcxpwla-nbvxtcpwlt-kkxmcztnyu
  - ./iudqbcujcd-ynukvjxgxw-nicdtugoxn
  - ./ivxjifbwbs-pmkpylhphv-jctdwuhqpe
  - ./ixtkyqihkv-imljloiqex-augjcvzgch
  - ./jcegwdirei-vaumuhoxie-bcwqnqadzl
  - ./jcfinelkzr-qctedwphye-ssbamdyxuz
  - ./jfshhjnzly-ceduaieezo-gdfnfdxggr
  - ./jnorbguptn-dzaygmoajz-wszsbnnhpg
  - ./jqdwjxzris-eimuxsbyoz-bhylakczsd
  - ./jrqqfpuace-ckjryxrdrw-trllbleiex
  - ./jsmgryfmpf-zaesxeuext-zxsbyrrrhp
  - ./jwjkdfxmsk-aqlvhafber-mgjybvzgea
  - ./jyikfaivsc-mhchvgdmxv-qdqsrsnxmt
  - ./jyuidzkmwm-xyxsdmyakh-ahvfbxeaha
  - ./jzkwdkcfrm-edzuwumizr-rgnvciqrvk
  - ./kaeynxdrei-dgomswchbk-wtcmryrwvb
  - ./kbzlyhdado-djamgamqav-jgwctjhnqy
  - ./kdmjlflvld-otcdbxojlx-vvoxlaenkf
  - ./khlobcypfq-pcvywhezot-bkjntvcfgx
  - ./khssayxcgh-pgglgjumki-lnynjqkofk
  - ./kmydpfguoy-dmlditoywj-jbanrjbeln
  - ./knlxweyfcf-ehyxlbsjov-czstiyephf
  - ./kqavalspcl-mjxvabybcy-rqybkwxafh
  - ./ksdzfutknl-ixfbxkyrgx-wxfwrtwscz
  - ./kvnpbwtwcj-dwnjcoxcjx-rsrcmzkshx
  - ./kvpcxfxkwh-ofoyasrlbb-moxeozkxbe
  - ./kxjfyqvjgh-gktxcmwtsj-nwnbfmdmgy
  - ./lbyeagpzai-mqklrvnslg-vtmfoaplrj
  - ./lceetnmgho-ryhynbzwbo-putrktyjrh
  - ./lcrrtskaqw-qcydsjdtme-gxhemiuzul
  - ./ldzbulfkvt-hofnssjwwf-zfzbqyxteu
  - ./ljcpnrxmqv-spomfvvntc-wxhqxrxhvn
  - ./lklojpplmm-gahraeiacr-nburlworaj
  - ./llmifepzfk-hsrksvrsdv-fgfwzuxjmz
  - ./llyutlisor-zrdktuzfng-yoiziohtux
  - ./lnbsavfifx-jvkkyhijuo-mwztyrysqo
  - ./lpzdcrcgmp-enmqmzibkz-prpxfuhosh
  - ./luljacqjym-uleizmtdpg-voznuwnupa
  - ./lvlhatycjj-iaeotfjvsm-kmlgcqvwbw
  - ./mbpugskatb-tiyjwpvxro-njveyigxha
  - ./mbtlirdcly-fwzdqeawms-zqmcmpuoeu
  - ./mdoykpipvg-mkkzuyqaxq-vjaxuxjyad
  - ./mgocxjmugg-szydfszzpd-rcfzbgiwzv
  - ./mgwcqgldiy-kcbfqcpdfb-jnytwvtarc
  - ./mhohanfufm-ymffrtobtc-qfcksznvxq
  - ./mjibzvuwhs-kggqbkkqva-qcbtnsewyz
  - ./mnjpisgook-hwiqblnzwl-ehpynslgbd
  - ./mqlghfymqs-ezmknnynin-uhinoznsmp
  - ./mqwtlpwidx-jmlbdwcrwk-cfkbdgeavf
  - ./mumgynkpga-etztcpawdt-qyssznhkrs
  - ./mvkqxbxlml-kgyjsqrevv-keazydjuzc
  - ./mxeaouxbfs-bsrlnhcxwc-lvdqaxcqtu
  - ./mxfcdkidxh-wfmvomxunv-volvdjmfuo
  - ./myyiorzlaw-ytvxbbmdpx-febkukndni
  - ./nayaepihad-ahzciepdny-xqpqcpnvbv
  - ./nbpvxcqiih-kifutcfxel-yxbuxwaxvc
  - ./nczwpbuqho-nyaejhutsu-qcntdbfxol
  - ./ndelfkyjip-gstihwuhfi-rjxxewsebt
  - ./nebfuwggyx-gaktiktcnq-rarmqbnkzf
  - ./nklcuwcmcz-rrzkeehbms-fufisqpxdt
  - ./nqooyfnfiy-cqxaludxua-uraxyfhmjz
  - ./oakbqnowyt-rkqwjgigvj-mmuscmokhh
  - ./ohouqyigpw-lndaiynzye-fcsmggspsv
  - ./ojfbtzpcfi-apxmpdnheh-xufedojzlq
  - ./opmzrinbix-dwnjuztviv-lhnefavumr
  - ./oqnwogrdyu-jcnnczqyvy-hdpyhkjidz
  - ./othbhqjnul-tazoftxenx-flrjltywxr
  - ./owoiqxteae-wtvcupsnfe-kgakffrwbr
  - ./phfepeqnuu-tzcfeylnrk-wxkjpqaipk
  - ./plzkrostns-lqhtumrcwh-urckjilnbs
  - ./pvlpstgwdv-ssyeecmdfo-dyxijkjfba
  - ./pwhdsdnpky-ahahgsbqkk-slvncrvngc
  - ./pxdenbmfbv-whzlgttmrr-dxlcacmmbo
  - ./pxmakzoxwb-fijzzixsga-gjuqhknsmw
  - ./pxtkkfktom-ixtvvmcwub-fbsbtnbddu
  - ./qbndygasus-dynhknvyvf-dqlbzywbrg
  - ./qdziqvbwej-qcftyzvsdf-yolbjmhgxb
  - ./qivxmeiywc-jecrjyijco-tprliqfsfi
  - ./qkyjwmgohp-inclbwiknw-pvbzlylyot
  - ./qlcdpjirst-utqhnvujil-xcrcnayaqt
  - ./qobthhtcsd-gkgnekbvsk-bkydljydgw
  - ./qutswcwzml-vwxhckvrrc-ycjsahqmdy
  - ./qvasxrulmh-hkqryfmwwu-wbiunuatjc
  - ./qvrbmctarr-jdixlpvffc-xosbzozjui
  - ./qzacujuixq-fcgnmtcbmf-pnwvpkfkpq
  - ./raqdrsxzcv-attoygtjjq-qbwfpkdtcm
  - ./raunigjedv-ifwpaynsww-ekopxefbiv
  - ./rgswdytbva-icqvrykamf-uigufjvtxz
  - ./rnxlejaloz-yuvvexhhzr-ivfpeumqge
  - ./rontohsvqd-kzkpimemzd-odglltphce
  - ./rpafndpsic-myjzrytxbk-itdubcwmii
  - ./rpamwcgsyt-bvsfivbjcy-llvtjqdqra
  - ./rqfouaqhgm-nxvkrcadip-armiklgokp
  - ./rqrhrfngcb-lhrmfapvdl-uebrqoygak
  - ./rsncqgtwnb-gxwvbahrpd-quhadaaeis
  - ./rusqthjvvk-pkxwsdwwhn-mwgnjefqfw
  - ./rytzenhuwi-ifmlrhcceo-gawhrxxqam
  - ./saidrignjp-borjrkntbw-jxnxtatreb
  - ./sboerrxqie-qaooqvidfh-rdjdiropml
  - ./sdmemwqaef-zvyohazcxc-tfrypmqjyq
  - ./sgvkleouab-fcrennpwqn-vqnmpcxqyw
  - ./shaqzilprc-cnvkkznmqt-osbygjlcfq
  - ./sjywzbvzez-scteewdihq-qamzizyjfw
  - ./svjggidczx-klsmyehdey-hhszutopxk
  - ./taswpnhopu-fnmrhygmff-jzgushedcg
  - ./tbccaljfec-jlsockgxxr-aapixuyltq
  - ./tcpfemufbu-rkcdoxsqzg-srcipggjue
  - ./toqjmgsrfv-nouqirkvuc-ubtevxrbsz
  - ./tpsrwghbwd-zcbdhxlhkm-yqsbkfvtmc
  - ./tqyksnesar-upekkbojzt-wueuynnzzh
  - ./traedgtejy-dxdtlzbjko-kicveovpzi
  - ./trkplfabrj-vqbcqmmylp-dalptunfba
  - ./tupxqmyoqe-eamyawauun-xoeizboyfy
  - ./tvlvjqkonn-jeasuqcexy-rbrpjulwgi
  - ./twxalqbfhg-zduimuhrkd-vzvamenoxz
  - ./txfqencqpt-dlgmtvzucm-qgjjrzzhpo
  - ./tymfhhklxa-xgesckxlzc-rqrdbphqyl
  - ./tzdnwycbfe-eedgfzqujz-vdbfcumwyt
  - ./tzxxlogcui-czfejtajgt-cekpcvgynm
  - ./ucqkfzglee-jykxafzelb-vvbnbgkvra
  - ./udylspikdq-fbrcpxkytb-vsxkoyvxli
  - ./ufcseumbsb-onvrgktxnv-rttptmphfp
  - ./uhdauwmvxd-nvcxoslsto-wmmmgnesij
  - ./uhstochqxx-jmscqnuokd-icqmvjaqaq
  - ./uslahbwpjb-vdtqwxhxnj-hiqltqwrnx
  - ./uuxigdmzun-amwuhmpemv-ztieeybvdh
  - ./uykvoactrp-ydiwfyontg-tbacsvptwj
  - ./uzcastvvkm-ahrxsdiznz-bhdnnootlp
  - ./vaiprwaopn-ecnkobylek-oacfzkwxue
  - ./vbltcnoepb-bhzritxypd-erpaaootbj
  - ./vfenmvaqbs-ctmfgtfvto-pgyqosqxmc
  - ./vghsvugwnc-sobhsxydmt-hbfuxwixxn
  - ./vhpkbpdaab-qgchccpiko-nbaihjjvlj
  - ./vssceiekkq-wmakioxqzz-whljvapvpg
  - ./vulsdpompx-fiahihpbmu-tkeebysusq
  - ./wawyrqawgm-wbsnngvels-ymrzamzkul
  - ./wepkodevti-ogvcxbgggb-rbvcpjjuuj
  - ./wiukuwohog-vwjxvvfcnn-wyuvrdnwbt
  - ./wjcvquzmqj-ngmhegkhun-ozevzugvrv
  - ./wlwwrnkraj-hobpvmwqln-seaiuaziys
  - ./wmhxaymzih-boewssflof-sxocwsfytv
  - ./wnnqxxyjlv-fofbbgzfpm-cdfgfjnzud
  - ./wrsxalzuux-fkrmnzenbw-mlawexhwxe
  - ./xbzyruovta-rnmmmtmvhp-fwuvrkmhuu
  - ./xegqhquozf-zujwswbnpo-ucyudoatvk
  - ./xetwqvgmww-woaeagiyhy-xenoupdlax
  - ./xghlolyoos-nlcnkznbnm-zjsjlqbprk
  - ./xhvnvefdcj-dtnyrqbkjj-eedsmvlriv
  - ./xloaentxga-mhkjxehlek-nvkifswcws
  - ./xmwnpwaspa-ifrscictqx-naqfoptqaq
  - ./xromcygenl-gojypjrqvs-nycfeqojfd
  - ./xsbdpdzvqi-tpyglsxlmh-awbcffuslv
  - ./xtwihehity-ujcjqxvexa-mtrhiynzie
  - ./xufvispsyn-onfrncdlrn-gzmzfszaoy
  - ./xwcfdydvlh-vojeneytpf-dmrwfoeouv
  - ./xzgooejkro-nofshmibln-ejyrcivdgr
  - ./yasnaowwla-aulvxrqdwx-qctutuqnpc
  - ./ydtkotmgcp-azuxdknkyc-gvybvqjofg
  - ./yeqzgwjcrl-ubgaozonrs-aabtyfwlqo
  - ./yghknvsgcz-tmltxosgbz-vzbmxaaypc
  - ./yhhtezsiap-fnkgdalzje-tdxkgqtftp
  - ./yjkwuakvbb-kyyojbhxic-bekeuwketn
  - ./yjtwzdarma-uscqahbujb-isdgvasdau
  - ./ylxoyzxian-hniypedaoa-dgahfygwnk
  - ./yqnzgbtjil-ajvkvudagy-yflacfcvwp
  - ./ysoetnsmhv-ssklecgxpx-vxycpvdukk
  - ./ysovwneqof-htzfreipkt-avvjcvvcdp
  - ./yyzlcedrhs-biepnnrljy-sdvwrcwbrs
  - ./yzcgtsyrps-zduxujtgzt-lxduqjsxtp
  - ./zblnwvepip-kjvrtssncl-wemnlpzrof
  - ./zpphqaohhd-blpklbpmiq-pgdhgxbdlu
  - ./zqlzfxaouu-ixmlfpdwfx-bvffwsusxw
  - ./zrowwqecdq-lueaquxzxq-nokjybdgyp
  - ./zvxosjlaim-rilcnymlpm-zokgocnrdo
  - ./zyjfwoiclj-qxpuxvslbs-twihlsityy

extra-deps: []

allow-newer: true
